LIBRARIES += src/plugins/sniff/libplugin_sniff
libplugin_sniff_MODULES := sniff task fork nop ping

$(O)/.objs/%.inc: $(S)/src/plugins/sniff/%
	$(M) SED $@
	$(Q)sed -e '/^#/d;s/\([\'\''"]\)/\\\1/g;s/^/"/;s/$$/\\n"/' $< >$@

$(O)/.objs/src/plugins/sniff/ping.o: $(O)/.objs/sniff-ping.inc
