#!/bin/ash

# Ucollect - small utility for real-time analysis of network data
# Copyright (C) 2014 CZ.NIC, z.s.p.o. (http://www.nic.cz/)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

while [ "$1" ] ; do
	PROTO="$1"
	COUNT="$2"
	SIZE="$3"
	HOST="$4"
	shift 4
	if echo "$HOST" | grep -q "'" ; then
		echo 'BAD INPUT';
		continue
	fi
	PARAMS=''
	case "$PROTO" in
		4)
			PARAMS="$PARAMS -4"
			;;
		6)
			PARAMS="$PARAMS -6"
			;;
		X)
			;;
		*)
			echo 'BAD INPUT'
			continue
			;;
	esac
	PARAMS="$PARAMS -c $COUNT -s $SIZE '$HOST'"
	eval "busybox ping $PARAMS" 2>/dev/null | sed -ne 's/.*(\(.*\)):.*/\1/p;s/.*seq=\([^ ]*\).*time=\([^ ]*\).*/\1:\2/p' | tr '\n' ' ' ; echo END
done
