# This file contains configuration of the build. It may be generated by some
# script in the future.

# The RELATIVE variable is for the wrapper makefiles.
O := $(RELATIVE).
S := $(RELATIVE).
ASCIIDOC := asciidoc
AR := ar
MAX_LOG_LEVEL := LOG_DEBUG_VERBOSE
PAGE_SIZE := $(shell getconf PAGE_SIZE)

include $(S)/Makefile.dir
