# This file contains configuration of the build. It may be generated by some
# script in the future.
O := .
S := .
ASCIIDOC := asciidoc
PAGE_SIZE := $(shell getconf PAGE_SIZE)

include $(S)/Makefile.dir
