# This file contains configuration of the build. It may be generated by some
# script in the future.

# The RELATIVE variable is for the wrapper makefiles.
O := $(RELATIVE).
S := $(RELATIVE).
CFLAGS += -latsha204 -luci -lpcap 
LINK_LIBRARIES += -latsha204 -luci -lpcap 
LDFLAGS_ALL += -latsha204 -luci -lpcap 
ASCIIDOC := asciidoc
AR := ar
MAX_LOG_LEVEL := LLOG_DEBUG_VERBOSE
PAGE_SIZE := $(shell getconf PAGE_SIZE)
ifneq ($(NO_MASTER),1)
ENABLE_PYTHON := 1
endif

include $(S)/Makefile.dir
