#!/bin/sh

set -e

q() {
	CMD="$1"
	NAME="$2"
	psql -q -d turris -1 -c "$CMD" | ./compact.pl | pbzip2 -5 >"$NAME".csv.bz2
	echo "Done $NAME on $(date +%X)" >&2
}

q "COPY (select remote, date(start_time), count(1) as attempt_count, 'ssh' from ssh_sessions where remote is not null group by date(start_time), remote) to STDOUT with CSV;" "ssh" &
q "COPY (select remote, date, attempt_count, server from fake_attackers where attempt_count > 0) to STDOUT with CSV;" "telnet" &
wait
