#!/bin/sh

# Import the data into database.

set -e

DIR=$(dirname "$0")

if [ '!' -x "$DIR/process/target/release/process" ] ; then
	echo "Please compile and provide the process executable"
	exit 1
fi

"$DIR/process/target/release/process" telnet.csv.bz2 ssh.csv.bz2 | "$DIR/to_db.pl" -i -d "$HOME/db.ini"
