#!/bin/sh

# Add incidents incrementally, from all the present csv files.

set -e

DIR=$(dirname "$0")

if [ '!' -x "$DIR/process/target/release/process" ] ; then
	echo "Please compile and provide the process executable"
	exit 1
fi

FILES=$(ls *.csv)
"$DIR/process/target/release/process" $FILES | "$DIR/to_db.pl" -d "$HOME/archivist.ini"
rm $FILES
