#!/bin/sh

. dbconfig

echo 'SELECT clients.name, count_snapshots.timestamp, count_types.name, counts.count, counts.size FROM counts JOIN count_snapshots ON counts.snapshot = count_snapshots.id JOIN clients ON clients.id = count_snapshots.client JOIN count_types ON count_types.id = counts.type ORDER BY count_snapshots.timestamp, clients.name, count_types.id;' | psql -U "$DBREAD" -d "$DB" -F'	' -q -t -A
