#!/bin/sh

DATE=$(date -d 'yesterday' +%Y-%m-%d)
DIR=$(dirname "$0")
if [ "$DIR" = "." ] ; then
	DIR=$(pwd)
fi

cd ~/fake-exports
# It is generated with the date +1, so eat it one day sooner
find -type f -mtime +7 -delete
"$DIR"/export_fake.pl "$DIR"/db.ini $DATE
chmod a+r *.csv
