#!/bin/sh

set -e

DIR="$1"
NAME="$2"
VERSION="$3"

mkdir -p "$DIR"
cd "$DIR"
gunzip -c | tar x
tar xf data.tar.gz
LIBNAME="$(echo $NAME | tr - _)"
LIBNAME="usr/lib/libplugin_${LIBNAME}_$VERSION.so"
sha1sum "$LIBNAME"
cd /
rm -rf "$DIR"
