#!/bin/sh

set -e

. ./dbconfig

LOCK_DIR=/tmp/refresh_blacklist_cache.lock

if ! mkdir "$LOCK_DIR" ; then
	echo "Already running?" 2>&1
	exit 1
fi

trap 'rm -rf "$LOCK_DIR"' EXIT INT QUIT TERM ABRT

(
	echo "BEGIN;"
	echo "DELETE FROM fake_blacklist_cache;"
	echo "INSERT INTO fake_blacklist_cache (server, remote, client, score, timestamp) SELECT server, remote, client, score, timestamp FROM fake_blacklist_cache_fill;"
	echo 'COMMIT;'
) | psql -U "$DBCLEANER" -d "$DB" $DBPARAMS


