LIBRARIES += src/core/libucollect_core
DOCS += $(addprefix src/core/,core uplink)

libucollect_core_MODULES := mem_pool util loop context packet uplink loader configure
libucollect_core_PKG_CONFIGS := zlib
