SCRIPTS += src/master/collectmaster
DOCS += src/master/collectmaster

collectmaster_SOURCE = collect-master.py

ifneq (,$(findstring ^$(RESTRICT),^src/master))
clean: clean-master
endif

.PHONY: clean-master

clean-master:
	rm -f $(wildcard $(S)/src/master/*.pyc $(S)/src/master/*/*.pyc)
