SCRIPTS += src/master/collectmaster
DOCS += src/master/collectmaster
LIBRARIES += src/master/atsha204

collectmaster_SOURCE = collect-master.py

atsha204_MODULES := atsha204
atsha204_SO_LIBS := crypto ssl unbound atsha204

ifneq (,$(findstring ^$(RESTRICT),^src/master))
clean: clean-master
endif

.PHONY: clean-master

clean-master:
	rm -f $(wildcard $(S)/src/master/*.pyc $(S)/src/master/*/*.pyc)
